package me.itangqi.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.itangqi.greendao.Note;
import me.itangqi.greendao.Note2;

import me.itangqi.greendao.NoteDao;
import me.itangqi.greendao.Note2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig note2DaoConfig;

    private final NoteDao noteDao;
    private final Note2Dao note2Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        note2DaoConfig = daoConfigMap.get(Note2Dao.class).clone();
        note2DaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        note2Dao = new Note2Dao(note2DaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Note2.class, note2Dao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        note2DaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public Note2Dao getNote2Dao() {
        return note2Dao;
    }

}
